### dataset setting
dataset: cddb
data_path: dil_dataset/CDDB
log_path: output
init_cls: 2
increment: 2
total_sessions: 5

task_name: ["gaugan", "biggan", "wild", "whichfaceisreal", "san"]
multiclass: [0, 0, 0, 0, 0]
class_order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

##################################################
### model base setting
model_name: soyo
net_type: soyo_clip
image_dim: 768
text_dim: 512
prompt_length: 10
hidden_dim: 64

### soyo
soyo_dim: 512
soyo_epoch: 30
soyo_lr: 0.1
soyo_weight_decay: 2.0e-4
##################################################

### model base training
init_epoch: 50
init_lr: 0.01
init_lr_decay: 0.1
init_weight_decay: 2.0e-4
epochs: 50
lr: 0.01
lr_decay: 0.1
weight_decay: 2.0e-4

batch_size: 128
seed: [0]
num_workers: 16

### other settings for CL
memory_size: 0
memory_per_class: 0
fixed_memory: true
shuffle: false
EPSILON: 1.0e-8