### dataset setting
dataset: core50
data_path: dil_dataset/CORe50
log_path: output
init_cls: 50
increment: 50
total_sessions: 8

##################################################
### model base setting
model_name: soyo
net_type: soyo_clip
image_dim: 768
text_dim: 512
prompt_length: 10
hidden_dim: 16

### soyo
soyo_dim: 512
soyo_epoch: 30
soyo_lr: 0.1
soyo_weight_decay: 2.0e-4
##################################################

### model base training
init_epoch: 20
init_lr: 0.01
init_lr_decay: 0.1
init_weight_decay: 2.0e-4
epochs: 20
lr: 0.01
lr_decay: 0.1
weight_decay: 2.0e-4

batch_size: 128
seed: [0]
num_workers: 16

### other settings for CL
memory_size: 0
memory_per_class: 0
fixed_memory: true
shuffle: false
EPSILON: 1.0e-8